### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-js-conditionals-uMDt4P#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-js-conditionals-uMDt4P/) and meets the following criteria:

- [x] Use the `prompt` and `confirm` functions (each at least once) to collect choices from the user (the entire story will take place in dialog boxes, so your `body` element could actually be empty, apart from the `script` element to include your JavaScript)
- [x] Use `if`, `else if`, and `else` to branch the story, based on user choices
- [x] In at least one branch, there should be at least 3 choices for the user to make
- [x] Include at least one branch where different things can happen each time with `Math.random()`
- [x] Use a logical operator (`&&` or `||`) at least once, where it makes sense
- [x] It should be impossible for an error to ever occur when playing your game, including handling for `null`/`undefined` where appropriate
- [x] All string input should be normalized, so that extra whitespace or a letter that's the wrong case will never cause a failed match
- [x] At least one number value is collected and used in a comparison (don't forget to convert it into a number first)
- [x] Don't get _too_ carried away -- it can be tempting to build a complex video game, but remember, you can always come back and build on this project later

It's suppost to keep track of your inventory but I couldn't do that without switching to a framework that used forms instead (because it never updates the screen).

**Comment by egillespie** [comment]
Hi @lordcrekit, this is a pretty wild idea. 🎲  I like where you're going with the adventure, and I have some suggestions to help improve it.

Since you pointed out that the inventory tracking is incomplete, I'll overlook those issues, but in general, I would recommend against including incomplete features in pull requests both here in class and in a professional setting. 😝 

### Please lint your files

Could you please jump back to the [previous lesson](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/js-collect-and-display-information/1) and follow the instructions to install the JavaScript linter in Atom?

Your `if`/`else if`/`else` is pretty cramped, making it hard to read. You also have some inconsistent formatting. Consistent formatting is an easy measure to take to avoid bugs. ;)

### No `conclusion-good.html`

It took some effort, but after many continues, my party was able to find their way through the cave unscathed. As they exited, an unavoidable 404 Not Found page crushed them.

### Pick one of `d20.js` or `Math.random`

I got excited and hopefully when I saw `d20.js` in your project, but I see you're only using it to generate the result of `1d20` rolls. You can accomplish the same effect with the following code, and remove the extra payload from your adventure:

```js
Math.floor((Math.random() * 20) + 1)
```

Frameworks are great when you need to save time or specialized functionality, but you also need to weigh the download time and feature bloat against what you're actually trying to accomplish. I recommend either removing `d20.js` from your project or replacing all of your other usages of `Math.random` with other calls to `d20` so that your adventure is fully committed to using the framework for game randomization. ;)

### More normalization on direction choice

If I typed "Left", I do not get the same result as if I had typed "left". I recommend calling `.toLowerCase()` to normalize the direction so that "left", "Left", and "LEFT" all mean the same thing.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by lordcrekit** [comment]
I can't believe I forgot the conclusion page. I think I just stopped testing whenever it popped the message, and never actually clicked okay.

Used npm standard to lint js files. Its throwing a few warnings but only because it doesn't know about d20, and because it wants me to use === for comparing strings.

Switched over to entirely using d20 for random.

**Comment by egillespie** [comment]
Ahhh, much better! Everything works great now and the code looks beautiful. Can't wait to see the roguelike version. :shipit:
